services:
  postgres:
    image: postgres:16-alpine
    container_name: gold-vn-postgres
    environment:
      POSTGRES_DB: gold_vn_track
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gold_vn_track"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
